### ISSUE TITLE
Page 105:  PromiseArray isFulfilled not working as intended

### ISSUE THREAD

**Issue by sirneb** [abuiles/ember-cli-101-errata#148]
I believe the intended effect is to reload articles every time except the first time when the index route gets triggered.  "isFulfilled" doesn't seem to work that way even when articles are already populated.  This can easily be tested when I go to articles/new and go back to articles/index, no xhr request were made.  It does seem to work when we navigate to the friends index and go that friend again.

**Comment by abuiles** [comment]
@sirneb which is your Ember-Data version?

**Comment by sirneb** [comment]
1.0.0-beta.12 with ember 1.9.1

**Comment by abuiles** [comment]
@sirneb can you try updating to 14.1 ? (just change it in the bower.json) that should fix the problem.

**Comment by sirneb** [comment]
@abuiles just tried it, it doesn't fix the issue.  You can probably duplicate this oddity by going to the articles index route then press "lend articles" then press "cancel".  No XHR request is made there.  If I set a debugger breakpoint in the index route before the `if (articles.get('isFulfilled')` while following those steps described, the debugger triggers(meaning it is hitting the route) and `articles.get('isFulfilled')` is indeed false while `articles.get('length')` is not zero.

**Comment by jbinto** [comment]
+1, this is very confusing. It seems flaky to rely on `isFulfilled` for anything.

Another way this fails to work is the following:
- 1) Start the app from scratch, go to Friends.
- 2) Click on a friend. `isFulfilled` is false, but Ember automagically loads the async relationship for the first time, so this is ok.
- 3) Click back.
- 4) Click on the same friend. `isFulfilled` is false still, so we have stale data.
- 5) Click back.
- 6) Click on the same friend. `isFulfilled` is now true, so we reload.

Steps 3-6 will repeat infinitely now. On **every other** try, the model will be reloaded, but in between it remains stale.

```
 DEBUG: Ember      : 1.10.0
 DEBUG: Ember Data : 1.0.0-beta.15
```
