### ISSUE TITLE
Page 74: should be index.js

### ISSUE THREAD

**Issue by kgish** [abuiles/ember-cli-101-errata#62]
`app/routes/articles/index`

should be:

`app/routes/articles/index.js`

**Comment by abuiles** [comment]
I believe this is fixed ? can you check against the latest version.

**Comment by kgish** [comment]
No this is not fixed. I downloaded the latest version which was emailed to me a couple days ago.

**Comment by abuiles** [comment]
Can you try downloading from the website? I'll send a release email later today

—

**Comment by kgish** [comment]
Fixed in the latest version which I just downloaded, thanks.

**Comment by abuiles** [comment]
thanks!
